<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Reportman.Reporting\Reportman.Reporting.csproj" />
    <ProjectReference Include="..\..\Reportman.Drawing.CrossPlatform\Reportman.Drawing.CrossPlatform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="Icu4c.Win.Min" Version="59.1.7" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

</Project>
